# Generated by Django 4.0.1 on 2022-09-06 18:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_remove_item_id_alter_file_filedate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='itemID',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='file',
            name='fileDate',
            field=models.DateField(default=datetime.datetime(2022, 9, 6, 11, 31, 14, 371369), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemDate',
            field=models.DateField(default=datetime.datetime(2022, 9, 6, 11, 31, 14, 371369), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemName',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
    ]
