# Generated by Django 4.0.1 on 2022-09-06 18:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_item_itemid_alter_file_filedate_alter_item_itemdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='fileDate',
            field=models.DateField(default=datetime.datetime(2022, 9, 6, 11, 31, 34, 874308), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemDate',
            field=models.DateField(default=datetime.datetime(2022, 9, 6, 11, 31, 34, 874308), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
